# .github/workflows/deploy.yml
name: Build and Deploy Blogger API Site

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout kode sumber
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    # --- TAMBAHKAN LANGKAH DEBUGGING INI ---
    - name: Print all environment variables (for debugging)
      run: |
        printenv
        # Atau untuk lebih spesifik:
        echo "BLOGGER_API_KEY value: AIzaSyBglonTK3lbLZwqYKSuI3Vj64HUbdPWq6s"
        echo "BLOG_ID value: 8601707668889540603"
      # Tambahkan `continue-on-error: true` jika Anda khawatir ini akan menghentikan build
      # (tapi harusnya tidak)
      continue-on-error: true
    # --- AKHIR LANGKAH DEBUGGING ---

    - name: Jalankan skrip build Python
      run: python src/build.py

    - name: Deploy ke GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        publish_branch: gh-pages
        force_orphan: true
